### ISSUE TITLE
panic: required key SECURITY_USER_NAME missing value

### ISSUE THREAD

**Issue by macevil** [cf-platform-eng/kibosh#9]
hi, i tried to install kibosh-0.0.37.linux on ubuntu and get the following error:

```
{"timestamp":"1527236782.223800659","source":"kibosh","message":"kibosh.Starting PKS Generic Broker","log_level":1,"data":{}}
{"timestamp":"1527236782.223932266","source":"kibosh","message":"kibosh.Loading config file","log_level":3,"data":{"error":"required key SECURITY_USER_NAME missing value","trace":"goroutine 1 [running]:\ngithub.com/cf-platform-eng/kibosh/vendor/code.cloudfoundry.org/lager.(*logger).Fatal(0xc4200a0a80, 0x1920581, 0x13, 0x1a79c80, 0xc4204b9670, 0x0, 0x0, 0x0)\n\t/go/src/github.com/cf-platform-eng/kibosh/vendor/code.cloudfoundry.org/lager/logger.go:132 +0xca\nmain.main()\n\t/go/src/github.com/cf-platform-eng/kibosh/main.go:39 +0xbb9\n"}}
{"timestamp":"1527236782.223932266","source":"kibosh","message":"kibosh.Loading config file","log_level":3,"data":{"error":"required key SECURITY_USER_NAME missing value","trace":"goroutine 1 [running]:\ngithub.com/cf-platform-eng/kibosh/vendor/code.cloudfoundry.org/lager.(*logger).Fatal(0xc4200a0a80, 0x1920581, 0x13, 0x1a79c80, 0xc4204b9670, 0x0, 0x0, 0x0)\n\t/go/src/github.com/cf-platform-eng/kibosh/vendor/code.cloudfoundry.org/lager/logger.go:132 +0xca\nmain.main()\n\t/go/src/github.com/cf-platform-eng/kibosh/main.go:39 +0xbb9\n"}}
panic: required key SECURITY_USER_NAME missing value

goroutine 1 [running]:
github.com/cf-platform-eng/kibosh/vendor/code.cloudfoundry.org/lager.(*logger).Fatal(0xc4200a0a80, 0x1920581, 0x13, 0x1a79c80, 0xc4204b9670, 0x0, 0x0, 0x0)
	/go/src/github.com/cf-platform-eng/kibosh/vendor/code.cloudfoundry.org/lager/logger.go:154 +0x504
main.main()
	/go/src/github.com/cf-platform-eng/kibosh/main.go:39 +0xbb9
```

**Comment by cholick** [comment]
See https://github.com/cf-platform-eng/kibosh/blob/master/local_dev.sh.template for required environment variables.
